//! Error types for the Tipz contract.

use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ContractError {
    NotInitialized = 1,
    AlreadyInitialized = 2,
    NotAuthorized = 3,
    AdminChangeAlreadyPending = 4,
    AdminChangeTimelockNotMet = 5,
    NoPendingAdmin = 6,
    ContractPaused = 7,
    NotRegistered = 8,
    AlreadyRegistered = 9,
    UsernameTaken = 10,
    InvalidUsername = 11,
    InvalidDisplayName = 12,
    InvalidAmount = 13,
    InsufficientBalance = 14,
    BalanceNotZero = 15,
    OverflowError = 16,
    NotFound = 17,
    ProfileDeactivated = 18,
    ProfileNotDeactivated = 19,
    MessageTooLong = 20,
    InvalidImageUrl = 21,
    BatchTooLarge = 22,
    InvalidFee = 23,
    CannotTipSelf = 24,
    NotVerified = 25,
    AlreadyVerified = 26,
    RateLimitExceeded = 27,
    TipBelowMinimum = 28,
    BelowCreatorMinimum = 29,
    InvalidDomain = 30,
    InvalidInput = 31,
    TokenNotAccepted = 32,
    MaxProfilesReached = 33,
    RefundWindowExpired = 34,
    RefundAlreadyRequested = 35,
    RefundAlreadyProcessed = 36,
    NotTipper = 37,
    NotCreator = 38,
    TipperBlocked = 39,
    BlocklistLimitReached = 40,
    ContractNotPaused = 41,
    EmergencyWithdrawalNotAllowed = 42,
    AdminProposalExpired = 43,
    MigrationAlreadyCompleted = 44,
    MigrationDowngradeRejected = 45,
    InvalidMigrationVersion = 46,
    NoRefundRequest = 47,
    InvalidMessage = 48,
    SubscriptionLimitReached = 49,
    RefundRequestExpired = 50,
    ProposalExpired = 51,
}
